name: Ansible Playbook

on:
  pull_request:
    paths:
    - .github/workflows/build_mac.yml
    - ansible/playbooks/AdoptOpenJDK_Unix_Playbook/**
    branches:         
    - master

permissions:
  contents: read

jobs:
  build-macos:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
    steps:

    - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0

    - name: Install dependencies
      run: brew install ansible

    - name: Run Ansible Playbook
      run: |
        echo "localhost ansible_user=runner ansible_connection=local" > ansible/hosts
        set -eux
        cd ansible
        sudo ansible-playbook -i hosts playbooks/AdoptOpenJDK_Unix_Playbook/main.yml --skip-tags="hosts_file,hostname,brew_upgrade,brew_cu,kernel_tuning,adoptopenjdk,jenkins,nagios,superuser,swap_file,crontab"
